FROM jenkins/jenkins:lts-alpine

USER root

RUN apk add --no-cache docker \
  py-pip \
  python-dev \
  libffi-dev \
  openssl-dev \
  gcc \
  libc-dev \
  make \
  shadow

RUN pip install docker-compose

# When running the service I need to set --group-add to the GID of the host docker group
# run the following to get the id: echo $(stat -c '%g' /var/run/docker.sock)
# I running with docker-compose then group_add can be set in version 2s of the compose file
RUN usermod -aG docker jenkins

USER jenkins